services:
  db:
    image: postgres:15
    container_name: ciber_backend_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ciber_backend
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  api:
    build: .
    depends_on:
      - db
    environment:
      DefaultConnection: "Host=db;Port=5432;Database=ciber_backend;Username=postgres;Password=secret;SSL Mode=Disable"
      DOTNET_ENVIRONMENT: Development
    ports:
      - "5000:8080"

volumes:
  ciber_backend_db_data: